spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name  # MySQL 서버와 데이터베이스 이름 설정
    username: your_username                               # MySQL 사용자명
    password: your_password                               # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver           # MySQL 드라이버 클래스

  jpa:
    hibernate:
      ddl-auto: update                                    # 자동 테이블 생성/업데이트 (옵션: none, validate, update, create, create-drop)
    show-sql: true                                        # 실행된 SQL을 콘솔에 출력
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect      # MySQL 8.x 버전의 Hibernate 방언 설정
